config/routes.rb
Rails.application.routes.draw do

  root 'gamelobbies#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }

  get 'leaderboard/index'
  delete '/gamelobbies', to: 'gamelobbies#index'

  resources :bombermen
  resources :gamechats
  
  get 'gamelobbies/join/:id', to: 'gamelobbies#join_with_link'
  post 'gamelobbies/join', to: 'gamelobbies#join'
  post 'gamelobbies/leave', to: 'gamelobbies#leave'
  post '/gamelobbies/changethumbnail', to: 'gamelobbies#change_thumbnail'
  post '/gamelobbies/updatemap', to: 'gamelobbies#update_map'
  post 'gamelobbies/start/:id', to: 'gamelobbies#start_game'
  get 'gamelobbies/channelname/:id', to: 'gamelobbies#get_channel_name'
  resources :gamelobbies

  get 'bombermen/show/:id', to: 'bombermen#show'
  get 'bombermen/game/:id', to: 'bombermen#get_game'
  post 'bombermen/game/leave/:id', to: 'bombermen#leave'
  post 'bombermen/game/winner/:id', to: 'bombermen#set_winner'
  get 'bombermen/index'
  post 'bombermen/index', to: 'bombermen#perform_action'

  get 'login/index'
  get 'gamechats/index'

  get 'chat/index'
  post 'chat/index', to: 'chat#send_msg'
  post 'chat/create', to: 'chat#create'
  resources :chat
  post 'gamechats/sendMessage', to: 'gamechats#send_message'
  resources :gamechats

  get 'bombermen/index/:lobbyid', to: 'bombermen#index'

  post 'bombermen/adduser/:lobbyid/:username', to: 'bombermen#add_user'
  get 'bombermen/getusers/:lobbyid', to: 'bombermen#get_users'
  post 'bombermen/sendMovement', to: 'bombermen#broadcast_out'

  post 'chat/index', to: 'chat#send_msg'
  get 'about', :to => 'welcome#about'
  get 'welcome/index'
  get 'welcome/login', :to => redirect('../login.html.erb')

end

app/models/gamelobby.rb
class Gamelobby < ActiveRecord::Base

  # Overriding the usual way of setting db column.
  def userlist=(val)
    super(Array(val))
  end
end

app/controllers/gamelobbies_controller.rb
class GamelobbiesController < ApplicationController

  MAX_INT = 9999999
  MAX_USERS_PER_ROOM = 4

  # List of channels
  # Individual game lobby will have its channel generated dynamically and will
  # be stored as lobby_id in the database record
  GAME_LOBBIES_PUBLIC_CHANNEL = "game_lobbies_channel"

  # List of events
  LOBBIES_UPDATED_EVENT = "lobbies_updated_event"
  GAME_ROOM_UPDATED_EVENT = "game_room_updated_event"
  GAME_STARTED_EVENT = "game_started_event"

  before_action :set_gamelobby, only: [:show, :edit, :update, :destroy]

  # GET /gamelobbies
  # GET /gamelobbies.json
  def index
    @gamelobbies = Gamelobby.where("? < user_count AND user_count < ? AND game_started = ?", 0, MAX_USERS_PER_ROOM, false)
                     .order("user_count DESC")
  end

  def join_with_link

    id = params[:id]

    flash[:lobby_id] = "#{id}"

    respond_to do |format|
      format.html { redirect_to "/" }
      format.json { render :index, status: :ok, location: @gamelobby }
    end

  rescue ActiveRecord::RecordNotFound
    redirect_to "/"

  end

  # POST /gamelobbies/join
  def join

    # Get the corresponding game lobby
    id = params[:id]
    @gamelobby = Gamelobby.find(id)

    unless @gamelobby.nil? || @gamelobby[:user_list].length >= 4

      # Update the user count and list of users
      @gamelobby[:user_list] << current_user[:id]
      @gamelobby[:user_count] = @gamelobby[:user_list].length

      if @gamelobby.save
        broadcast(@gamelobby[:lobby_id], GAME_ROOM_UPDATED_EVENT, { :current_user_id => current_user[:id].to_s })
        broadcast(GAME_LOBBIES_PUBLIC_CHANNEL, LOBBIES_UPDATED_EVENT, {})

        # Store current user to the object
        data = {
          :current_user_id => current_user[:id].to_s,
          :channel_name => @gamelobby[:lobby_id]
        }
        render json: data, status: :ok, location: @gamelobby

      else
        render json: data.errors, status: :unprocessable_entity

      end

    else
      # This will gets rendered when the room is full, which may happend
      # when 2 or more users clicked on the same "join" button at the same time
      respond_to do |format|
        format.html { redirect_to "/", notice: 'The room is full!' }
        format.json { render :index, status: :unprocessable_entity}
      end
    end
  end

  # POST /gamelobbies/leave
  def leave

    # Get the corresponding game lobby
    id = params[:id]
    @gamelobby = Gamelobby.find(id)

    unless @gamelobby.nil?

      # Update the user count and list of users
      @gamelobby[:user_list].delete(current_user[:id].to_s)
      @gamelobby[:user_count] = @gamelobby[:user_list].length

      if @gamelobby.save

        # If there is no more user in the room, then delete the room
        if @gamelobby[:user_count] <= 0
          destroy
        else
          # Keep the room in the table if more users is in the room
          broadcast(@gamelobby[:lobby_id], GAME_ROOM_UPDATED_EVENT, { :current_user_id => current_user[:id].to_s })
          broadcast(GAME_LOBBIES_PUBLIC_CHANNEL, LOBBIES_UPDATED_EVENT, {})

          render json: @gamelobby, status: :created, nothing: true
        end

      else
        render json: @gamelobby.errors, status: :unprocessable_entity

      end

    else
      render json: @gamelobby.errors, status: :unprocessable_entity
    end
  end

  # POST /gamelobbies/changethumbnail
  def change_thumbnail

    user_id = params[:user_id]

    if current_user[:id].to_s == user_id.to_s

      # Find the User
      user = User.find(user_id.to_s)

      # Change the image path
      user[:image] = params[:image]

      if user.save
        data = { :current_user_id => current_user[:id].to_s }

        # Broadcast out
        broadcast(params[:channel_name], GAME_ROOM_UPDATED_EVENT, data)
        broadcast(GAME_LOBBIES_PUBLIC_CHANNEL, LOBBIES_UPDATED_EVENT, {})
      end

    end

    render nothing: true
  end

  def update_map

    id = params[:id]
    gamelobby = Gamelobby.find(id)

    old_map_id = gamelobby[:selected_map]

    # Make sure only the host can update the map
    unless gamelobby.nil?

      users = gamelobby[:user_list]

      if current_user[:id].to_s == users[0].to_s

        gamelobby[:selected_map] = params[:selected_map]

        if gamelobby.save

          broadcast(gamelobby[:lobby_id], GAME_ROOM_UPDATED_EVENT, { :current_user_id => current_user[:id].to_s } )

          render nothing: true
          return
        end
      end
    end

    # Reset back to old map ID because failed to update
    gamelobby[:selected_map] = old_map_id
    gamelobby.save

    render nothing: true
  end

  # POST /gamelobbies/channelname/start/1
  def start_game
    # Get the corresponding game lobby ID
    id = params[:id]
    @gamelobby = Gamelobby.find(id)

    unless @gamelobby.nil?

      users = @gamelobby[:user_list]

      # Make sure we only start the game if there are more than 1 persons
      # in the game room
      if users.length > 1

        # Make sure the person who start this game is the host
        host = users[0]
        if host.to_s == current_user[:id].to_s

          render json: { lobby_id: @gamelobby[:id],
                         game_name: @gamelobby[:lobby_name],
                         channel_name: @gamelobby[:lobby_id],
                         selected_map: @gamelobby[:selected_map],
                         user_list: @gamelobby[:user_list] },
                 status: :ok,
                 nothing: true

          return
        end
      end
    end

    render nothing: true
  end

  # GET /gamelobbies/channelname/1
  def get_channel_name

    # Get the corresponding game lobby
    id = params[:id]

    @gamelobby = Gamelobby.find(id)

    unless @gamelobby.nil?
      render json: { channel_name: @gamelobby[:lobby_id] }, status: :ok, nothing: true

    else
      render status: :unauthorized, nothing: true
    end
  end

  # GET /gamelobbies/1
  # GET /gamelobbies/1.json
  def show
  end

  # GET /gamelobbies/new
  def new
    @gamelobby = Gamelobby.new
  end

  # GET /gamelobbies/1/edit
  def edit
  end

  # POST /gamelobbies
  # POST /gamelobbies.json
  def create
    @gamelobby = Gamelobby.new(gamelobby_params)

    if @gamelobby.save
      broadcast(GAME_LOBBIES_PUBLIC_CHANNEL, LOBBIES_UPDATED_EVENT, {})

      render json: @gamelobby, status: :created, location: @gamelobby

    else
      render json: @gamelobby.errors, status: :unprocessable_entity

    end
  end

  # PATCH/PUT /gamelobbies/1
  # PATCH/PUT /gamelobbies/1.json
  def update
    respond_to do |format|
      if @gamelobby.update(gamelobby_params)
        broadcast(GAME_LOBBIES_PUBLIC_CHANNEL, LOBBIES_UPDATED_EVENT, {})

        format.html { redirect_to @gamelobby, notice: 'Gamelobby was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamelobby }
      else
        format.html { render :edit }
        format.json { render json: @gamelobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamelobbies/1
  # DELETE /gamelobbies/1.json
  def destroy
    begin
      @gamelobby.destroy

      broadcast(GAME_LOBBIES_PUBLIC_CHANNEL, LOBBIES_UPDATED_EVENT, {})

    rescue ActiveRecord::RecordNotFound
      # it's all good
    end

    render nothing: true

  end

  def show_room
    @show_room
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_gamelobby
    @gamelobby = Gamelobby.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gamelobby_params
    # Preset some parameter values
    {
      lobby_id: new_lobby_id,
      lobby_name: params[:name],
      public: params[:public],
      game_started: false,
      user_count: 1,
      user_list: [current_user[:id]]
    }
  end

  def new_lobby_id
    # Get the current time in miliseconds and hexadecimal format
    time = (Time.zone.now.to_f * 1000).to_i
    time_in_hex = time.to_s(16)

    # Get a random number in hexadecimal format
    rand_int = rand(MAX_INT)
    rand_int_in_hex = rand_int.to_s(16)

    # Combine both current time and random number to use as the lobby ID
    (time_in_hex + rand_int_in_hex).upcase
  end

  def broadcast(channels, event, data)
    # Include the socket ID because we want to exclude the sender as the recipient
    Pusher.trigger(channels, event, data, { socket_id: params[:socket_id] });
  end
end

app/helpers/gamelobbies_helper.rb
module GamelobbiesHelper
end

app/views/gamelobbies/_form.html.erb
<%= form_for(@gamelobby) do |f| %>
  <% if @gamelobby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamelobby.errors.count, "error") %> prohibited this gamelobby from being saved:</h2>

      <ul>
      <% @gamelobby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lobbyid %><br>
    <%= f.text_field :lobbyid %>
  </div>
  <div class="field">
    <%= f.label :lobbyname %><br>
    <%= f.text_field :lobbyname %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.text_field :public %>
  </div>
  <div class="field">
    <%= f.label :gamestarted %><br>
    <%= f.text_field :gamestarted %>
  </div>
  <div class="field">
    <%= f.label :usercount %><br>
    <%= f.text_field :usercount %>
  </div>
  <div class="field">
    <%= f.label :userlist %><br>
    <%= f.text_field :userlist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gamelobbies/edit.html.erb
<h1>Editing Gamelobby</h1>

<%= render 'form' %>

<%= link_to 'Show', @gamelobby %> |
<%= link_to 'Back', gamelobbies_path %>

app/views/gamelobbies/index.html.erb
<div id="current-user" data-user-id="<%= current_user[:id].to_s %>" style="display: none"></div>

<head>
  <link href='https://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "gamelobbies"%>
</head>

<body onLoad="preloadImages()">
<div id="gl-wrapper">

  <!-- Main Container -->
  <div id="gl-main-container">
    <div id="show-lobby" style="display: none;"><%= flash[:lobby_id] %></div>

    <!-- Header -->
    <div id="gl-header">
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header" id="gl-header-small">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gl-header-menu-buttons" aria-expanded="false">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <div class="gl-header-inner-nav">
            <a class="navbar-brand gl-title" href="#">BOMBERMAN</a>
            <div id="notice"><%= flash[:notice] %></div>
          </div>
        </div>

        <!-- Collect the nav links and other content for toggling -->
        <div class="collapse navbar-collapse" id="gl-header-menu-buttons" aria-expanded="false">
          <div class="gl-header-inner-nav">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="#" onclick="showGameLobbyList(null, true)">LOBBIES</a>
              </li>
              <li>
                <a href="#" onclick="showLeaderboard(true)">LEADERBOARD</a>
              </li>
              <li>
                <a href="/about.html">ABOUT US</a>
              </li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <!-- End Header -->

    <!-- Content -->
    <div id="gl-content">
      <div id="game-lobbies">

        <!-- The jQuery will replace this section with game room -->
        <div id="game-lobbies-content">
          <div id="gl-content-container">
            <div class="container-fluid">
              <div class="gl-container-content">

                <% i = 0 %>
                <% while i < @gamelobbies.length %>
                    <% if i % 3 == 0 %>

                        <!-- Add a new row, each row can only fit 3 boxes -->
                        <div class="row">
                          <% j = i %>
                          <% jend = j + 3 %>
                          <% while j < @gamelobbies.length && j < jend %>

                              <% gamelobby = @gamelobbies[j] %>
                              <% user = gamelobby.user_list[0] %>
                              <% user = User.find(user) %>
                              <% thumbnail = user[:image] %>

                              <% if user[:image].nil? || user[:image].to_s == "" %>
                                  <% thumbnail = "/assets/img_thumbnail_0.png" %>
                                  <% user[:image] = thumbnail %>
                                  <% user.save %>
                              <% end %>

                              <div class="col-sm-4">
                                <div class="gl-game-item-container">
                                  <div class="gl-title">
                                    <%= gamelobby.lobby_name %>
                                  </div>

                                  <hr/>

                                  <div class="gl-game-item">
                                    <div class="gl-game-item-left">
                                      <div class="img-user-thumbnail" style="background-image: url(<%= thumbnail %>)"></div>
                                    </div>
                                    <div class="gl-game-item-right">
                                      <span>HOST: <%= user.name %></span>
                                      <span><%= gamelobby.public ? "PUBLIC" : "PRIVATE" %></span>
                                      <span><%= gamelobby.user_list.length %> / 4</span>
                                    </div>
                                  </div>

                                  <hr/>

                                  <div class="gl-game-item-footer">
                                    <% if ! gamelobby.public %>
                                        <button class="btn btn-gl-custom disabled">JOIN</button>
                                    <% else %>
                                        <button class="btn btn-gl-custom" onclick="joinGameLobby(<%= gamelobby[:id] %>, true)">JOIN</button>
                                    <% end %>
                                  </div>
                                </div>
                              </div>

                              <% j = j + 1 %>
                          <% end %>
                        </div>
                    <% end %>

                    <% i = i + 3 %>
                <% end %>
              </div>
            </div>
          </div>

          <div id="game-lobbies-content-footer">
            <button class="btn btn-gl-custom" data-toggle="modal" data-target="#create-game-modal">CREATE GAME</button>
          </div>
        </div>
      </div>
    </div>
    <!-- End Content -->

    <!-- Sidebar -->
    <div id="gl-sidebar">
      <div id="chat-div"></div>
    </div>
    <!-- End Sidebar -->
  </div>
  <!-- End Main Container -->

  <!-- Footer -->
  <div id="gl-footer">

  </div>
  <!-- End Footer -->
</div>
</body>


<!-- Create Game Modal -->
<div id="create-game-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createGameModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="createGameModalLabel">
          Create Game
        </h4>
      </div>

      <!-- Modal Body -->
      <div class="modal-body">
        <form role="form">
          <div class="form-group">
            <label for="roomName">Room name</label>
            <input type="text" class="form-control" id="create-game-room-name" placeholder="Enter room name" maxlength="10"/>
          </div>
          <div class="form-group">
            <label for="publicprivate">Public/Private</label>
            <br>
            <select class="form-control" id="create-game-public-private" name="create-game-public-private">
              <option value="public">Public</option>
              <option value="private">Private</option>
            </select>
          </div>
        </form>
      </div>

      <!-- Modal Footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="showGameLobbyList(null, false)">Cancel</button>
        <button type="button" class="btn btn-success" onclick="createGameLobby()">OK</button>
      </div>
    </div>
  </div>
</div>

<!-- Error Message Modal -->
<div id="error-message-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="errorMessageLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="errorMessageLabel">
          Error
        </h4>
      </div>

      <!-- Modal Body -->
      <div class="modal-body" id="error-message-data"></div>

      <!-- Modal Footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal" onclick="showGameLobbyList(null, false)">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/gamelobbies/joinwithlink.js.erb
$("<%= escape_javascript(render @user) %>").appendTo("#users");

app/views/gamelobbies/new.html.erb
<h1>New Gamelobby</h1>

<%= render 'form' %>

<%= link_to 'Back', gamelobbies_path %>

app/views/gamelobbies/show.html.erb
<% users = @gamelobby[:user_list] %>
<% host = User.find(users[0].to_s) %>
<% map_paths = ["/assets/map_0.jpg", "/assets/map_1.jpg", "/assets/map_2.jpg"] %>


<body onLoad="preloadImages()">
<div id="game-room">

  <div id="gamelobby"
       data-id="<%= @gamelobby[:id] %>"
       data-channel-name="<%= @gamelobby[:lobby_id] %>"
       style="display: none"></div>

  <div id="game-lobbies-content">
    <div id="gr-content-container">
      <div class="container-fluid">
        <div class="gr-container-content">

          <!-- Game info and players' thumbnails -->
          <div class="row">
            <div id="game-info-players-thumbnails-container">
              <!-- Game room info -->
              <div class="col-sm-5">
                <div id="gr-info-container">
                  <div class="gr-title">
                    <%= @gamelobby[:lobby_name] %>
                  </div>

                  <hr/>

                  <div class="gr-content">
                    <!-- Create the URL for others to join -->
                    <% url_without_id = request.original_url.to_s[0..request.original_url.to_s.rindex("/")] %>
                    <% complete_url = "#{url_without_id}join/#{@gamelobby[:id]}" %>
                    <span class="glyphicon glyphicon-link" style="-moz-user-select: all;
                            -webkit-user-select: all;
                            user-select: all;
                            cursor: auto"><i><%= complete_url %></i></span>
                  <span>HOST&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    :&nbsp;&nbsp;<i><%= host[:name] %></i>
                  </span>
                    <span>PUBLIC / PRIVATE :&nbsp;&nbsp;<i><%= @gamelobby[:public] ? "PUBLIC" : "PRIVATE" %></i></span>
                  <span>PLAYERS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    :&nbsp;&nbsp;<i><%= users.length %></i>
                  </span>
                  </div>
                </div>
              </div>
              <!-- End Game room info -->

              <!-- Players thumbnails -->
              <div class="col-sm-5">
                <div id="gr-players-container">
                  <div class="container-fluid">
                    <!-- Player 1 and 2 -->
                    <div class="row">
                      <!-- Player 1 -->
                      <div class="col-sm-6">
                        <div class="player-info">
                          <% name = "" %>
                          <% image = "/assets/img_thumbnail_0.png" %>
                          <% user = users[0].nil? ? nil : User.find(users[0]) %>
                          <% if ! user.nil? %>
                              <% name = user[:name] %>

                              <% if ! user[:image].nil? && user[:image].length > 0 %>
                                  <% image = user[:image] %>
                              <% end %>
                          <% end %>

                          <% if current_user[:id].to_s == user.id.to_s %>
                              <div class="image-with-selection">
                                <img id="img-thumbnail" class="img-user-thumbnail" src=<%= image %> />
                                <div id="image-selection-arrow-container">
                                  <div id="image-selection-arrow" onclick="nextThumbnail()"></div>
                                </div>
                              </div>

                          <% else %>
                              <div class="img-user-thumbnail" style="background-image: url(<%= image %>)"></div>
                          <% end %>

                          <div class="player-info-name"><%= name %></div>
                        </div>
                      </div>

                      <!-- Player 2 -->
                      <div class="col-sm-6">
                        <div class="player-info">
                          <% name = "" %>
                          <% image = "/assets/img_thumbnail_0.png" %>
                          <% user = users[1].nil? ? nil : User.find(users[1]) %>
                          <% if ! user.nil? %>
                              <% name = user[:name] %>

                              <% if ! user[:image].nil? && user[:image].length > 0 %>
                                  <% image = user[:image] %>
                              <% end %>
                          <% end %>

                          <% if ! user.nil? && current_user[:id].to_s == user.id.to_s %>
                              <div class="image-with-selection">
                                <img id="img-thumbnail" class="img-user-thumbnail" src=<%= image %> />
                                <div id="image-selection-arrow-container">
                                  <div id="image-selection-arrow" onclick="nextThumbnail()"></div>
                                </div>
                              </div>

                          <% else %>
                              <div class="img-user-thumbnail" style="background-image: url(<%= image %>)"></div>
                          <% end %>

                          <div class="player-info-name"><%= name %></div>
                        </div>
                      </div>
                    </div>

                    <!-- Player 3 and 4 -->
                    <div class="row">
                      <!-- Player 3 -->
                      <div class="col-sm-6">
                        <div class="player-info">
                          <% name = "" %>
                          <% image = "/assets/img_thumbnail_0.png" %>
                          <% user = users[2].nil? ? nil : User.find(users[2]) %>
                          <% if ! user.nil? %>
                              <% name = user[:name] %>

                              <% if ! user[:image].nil? && user[:image].length > 0 %>
                                  <% image = user[:image] %>
                              <% end %>
                          <% end %>

                          <% if ! user.nil? && current_user[:id].to_s == user.id.to_s %>
                              <div class="image-with-selection">
                                <img id="img-thumbnail" class="img-user-thumbnail" src=<%= image %> />
                                <div id="image-selection-arrow-container">
                                  <div id="image-selection-arrow" onclick="nextThumbnail()"></div>
                                </div>
                              </div>

                          <% else %>
                              <div class="img-user-thumbnail" style="background-image: url(<%= image %>)"></div>
                          <% end %>

                          <div class="player-info-name"><%= name %></div>
                        </div>
                      </div>

                      <!-- Player 4 -->
                      <div class="col-sm-6">
                        <div class="player-info">
                          <% name = "" %>
                          <% image = "/assets/img_thumbnail_0.png" %>
                          <% user = users[3].nil? ? nil : User.find(users[3]) %>
                          <% if ! user.nil? %>
                              <% name = user[:name] %>

                              <% if ! user[:image].nil? && user[:image].length > 0 %>
                                  <% image = user[:image] %>
                              <% end %>
                          <% end %>

                          <% if ! user.nil? && current_user[:id].to_s == user.id.to_s %>
                              <div class="image-with-selection">
                                <img id="img-thumbnail" class="img-user-thumbnail" src=<%= image %> />
                                <div id="image-selection-arrow-container">
                                  <div id="image-selection-arrow" onclick="nextThumbnail()"></div>
                                </div>
                              </div>

                          <% else %>
                              <div class="img-user-thumbnail" style="background-image: url(<%= image %>)"></div>
                          <% end %>

                          <div class="player-info-name"><%= name %></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- End players thumbnails -->
            </div>
          </div>
          <!-- End Game info and players' thumbnails -->

          <!-- Map selection -->
          <div class="row">
            <div id="map-selection-container">
              <div class="gr-title">
                MAPS
              </div>

              <hr/>

              <div id="map-content">
                <div class="container-fluid">

                  <% i = 0 %>
                  <% while i < map_paths.length %>

                    <!-- Add new row -->
                    <div class="row">
                      <% j = i %>
                      <% while j < map_paths.length %>
                        <% selected_map_call = "selectedMap(" + j.to_s + ")" %>
                        <div class="map-image-button-container col-sm-3">
                          <label>
                            <input class="map-image-button" type="radio" name="maps" value="<%= j %>"
                              <%= current_user[:id].to_s == host[:id].to_s ? "" : "disabled" %>
                              <%= current_user[:id].to_s == host[:id].to_s ? "onclick=" + selected_map_call : "" %>
                            />

                            <img class="img-responsive <%= current_user[:id].to_s == host[:id].to_s ? "" : "disable-hover" %> <%= @gamelobby[:selected_map] == j ?  "checked-map" : "" %>"
                              src="<%= map_paths[j] %>" >
                          </label>
                        </div>

                        <% j = j + 1 %>
                      <% end %>
                    </div>

                    <% i = i + 4 %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <!-- End Map selection -->
        </div>
      </div>
    </div>

    <div id="gr-content-footer">
      <button class="btn btn-gl-custom btn-gl-cancel" onclick="leaveGameLobby(<%= @gamelobby.id %>, true)">LEAVE</button>

      <!-- Only the host can start the game -->
      <% users = @gamelobby[:user_list] %>
      <% if current_user[:id].to_s == host[:id].to_s %>
        <button class="btn btn-gl-custom" onclick="startGame(<%= @gamelobby.id %>)">START GAME</button>
      <% else %>
        <button class="btn btn-gl-custom disabled">START GAME</button>
      <% end %>
    </div>
  </div>

  <div id="loading-screen"></div>

</div>

</body>