config/routes.rb
Rails.application.routes.draw do

  root 'gamelobbies#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }

  get 'leaderboard/index'
  delete '/gamelobbies', to: 'gamelobbies#index'

  resources :bombermen
  resources :gamechats
  
  get 'gamelobbies/join/:id', to: 'gamelobbies#join_with_link'
  post 'gamelobbies/join', to: 'gamelobbies#join'
  post 'gamelobbies/leave', to: 'gamelobbies#leave'
  post '/gamelobbies/changethumbnail', to: 'gamelobbies#change_thumbnail'
  post '/gamelobbies/updatemap', to: 'gamelobbies#update_map'
  post 'gamelobbies/start/:id', to: 'gamelobbies#start_game'
  get 'gamelobbies/channelname/:id', to: 'gamelobbies#get_channel_name'
  resources :gamelobbies

  get 'bombermen/show/:id', to: 'bombermen#show'
  get 'bombermen/game/:id', to: 'bombermen#get_game'
  post 'bombermen/game/leave/:id', to: 'bombermen#leave'
  post 'bombermen/game/winner/:id', to: 'bombermen#set_winner'
  get 'bombermen/index'
  post 'bombermen/index', to: 'bombermen#perform_action'

  get 'login/index'
  get 'gamechats/index'

  get 'chat/index'
  post 'chat/index', to: 'chat#send_msg'
  post 'chat/create', to: 'chat#create'
  resources :chat
  post 'gamechats/sendMessage', to: 'gamechats#send_message'
  resources :gamechats

  get 'bombermen/index/:lobbyid', to: 'bombermen#index'

  post 'bombermen/adduser/:lobbyid/:username', to: 'bombermen#add_user'
  get 'bombermen/getusers/:lobbyid', to: 'bombermen#get_users'
  post 'bombermen/sendMovement', to: 'bombermen#broadcast_out'

  post 'chat/index', to: 'chat#send_msg'
  get 'about', :to => 'welcome#about'
  get 'welcome/index'
  get 'welcome/login', :to => redirect('../login.html.erb')

end

app/models/gamechat.rb
class Gamechat < ActiveRecord::Base
end

app/controllers/gamechats_controller.rb
class GamechatsController < ApplicationController

  PUBLIC_CHAT_CHANNEL = "public_chat_channel"
  CHAT_MSG_RECEIVED_EVENT = "chat_msg_received_event"

  before_action :set_gamechat, only: [:show, :edit, :update, :destroy]

  before_filter :get_name
	require 'pusher'

	Pusher.app_id = '151801'
	Pusher.key = '446412644b608e9db0ec'
	Pusher.secret = 'e2a6cf311b4bbe9e69df'

  # GET /gamechats
  # GET /gamechats.json
  def index
    @gamechats = Gamechat.all
    @username = current_user.name
    @user_id = current_user[:id]
  end

  # GET /gamechats/1
  # GET /gamechats/1.json
  def show
  end

  # GET /gamechats/new
  def new
    @gamechat = Gamechat.new
  end

  # GET /gamechats/1/edit
  def edit
  end

  # POST /gamechats
  # POST /gamechats.json
  def create
    @gamechat = Gamechat.new(gamechat_params)

    respond_to do |format|
      if @gamechat.save
        format.html { redirect_to @gamechat, notice: 'Gamechat was successfully created.' }
        format.json { render :show, status: :created, location: @gamechat }
      else
        format.html { render :new }
        format.json { render json: @gamechat.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_message

    data = {
      :name => @username,
      :message => params[:message],
      :sender_id => current_user[:id]
    }

    # Broadcast out to receivers
		Pusher.trigger(params[:channel_name], CHAT_MSG_RECEIVED_EVENT, data)

    render nothing: true

  end 
  def get_name
  	@username = current_user.name
  end

  # PATCH/PUT /gamechats/1
  # PATCH/PUT /gamechats/1.json
  def update
    respond_to do |format|
      if @gamechat.update(gamechat_params)
        format.html { redirect_to @gamechat, notice: 'Gamechat was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamechat }
      else
        format.html { render :edit }
        format.json { render json: @gamechat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamechats/1
  # DELETE /gamechats/1.json
  def destroy
    @gamechat.destroy
    respond_to do |format|
      format.html { redirect_to gamechats_url, notice: 'Gamechat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamechat
      @gamechat = Gamechat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gamechat_params
      params.require(:gamechat).permit(:lobbyid, :message)
    end
end

app/helpers/gamechats_helper.rb
module GamechatsHelper
end

app/views/gamechats/_form.html.erb
<%= form_for(@gamechat) do |f| %>
  <% if @gamechat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamechat.errors.count, "error") %> prohibited this gamechat from being saved:</h2>

      <ul>
      <% @gamechat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lobbyid %><br>
    <%= f.text_area :lobbyid %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gamechats/edit.html.erb
<h1>Editing Gamechat</h1>

<%= render 'form' %>

<%= link_to 'Show', @gamechat %> |
<%= link_to 'Back', gamechats_path %>

app/views/gamechats/index.html.erb
 <%= stylesheet_link_tag 'chat' %>

  <input type="button" name="toggleChat" value="toggle" />

<p id="notice"><%= notice %></p>

<h1>Listing Gamechats</h1>
  <input type="button" name="toggle" value="toggle" onclick="chatBox"/>
      <div>
        <button type="button" onclick="abc()">Create Game</button>
      </div>
<div id="chat_div"></div>
<!-- <table>
  <thead>
    <tr>
      <th>Lobbyid</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gamechats.each do |gamechat| %>
      <tr>
        <td><%= gamechat.lobbyid %></td>
        <td><%= gamechat.message %></td>
        <td><%= link_to 'Show', gamechat %></td>
        <td><%= link_to 'Edit', edit_gamechat_path(gamechat) %></td>
        <td><%= link_to 'Destroy', gamechat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 -->
<br>

app/views/gamechats/new.html.erb
<h1>New Gamechat</h1>

<%= render 'form' %>

<%= link_to 'Back', gamechats_path %>

app/views/gamechats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lobbyid:</strong>
  <%= @gamechat.lobbyid %>
</p>

<p>
  <strong>Message:</strong>
  <%= @gamechat.message %>
</p>

<%= link_to 'Edit', edit_gamechat_path(@gamechat) %> |
<%= link_to 'Back', gamechats_path %>